# Generated by Django 4.2.5 on 2023-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_foro_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoHabilitacionAlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoId', models.IntegerField()),
                ('cursoTitulo', models.CharField(max_length=100)),
                ('cursoDocenteId', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('id_alumno', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('pagado', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField()),
                ('altaInscripcion', models.BooleanField(default=False)),
            ],
        ),
    ]
