# Generated by Django 4.2.3 on 2023-10-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="Apellido")),
                ("email", models.EmailField(max_length=150, verbose_name="E-mail")),
                ("edad", models.CharField(verbose_name="Edad")),
            ],
        ),
    ]
