# Generated by Django 4.2.5 on 2023-10-24 03:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoInscripto',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('legajo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='course',
            name='titulo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cursoinscripto')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursoInscripto',
            field=models.ManyToManyField(through='courses.inscripcion', to='courses.cursoinscripto'),
        ),
        migrations.AddField(
            model_name='course',
            name='docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.docente'),
            preserve_default=False,
        ),
    ]
