# Generated by Django 4.2.5 on 2023-11-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_inscripcion_activo_inscripcion_habilitado'),
        ('courses', '0003_pagohabilitacionalumnocurso'),
    ]

    operations = [
    ]
