# Generated by Django 4.2.5 on 2023-11-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_20231119_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoHabilitacionAlumnoCurso',
        ),
    ]
