# Generated by Django 4.2.5 on 2023-10-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_userlist_cursoinscripto_habilitado_estudiante_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Activo',
            new_name='activo',
        ),
    ]
