# Generated by Django 4.2.5 on 2023-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_activo_estudiante_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='altura',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='Completar'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(default='Completar', max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(default='Completar', max_length=100),
        ),
    ]
