# Generated by Django 4.2.5 on 2023-11-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_direccion_altura_alter_direccion_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='cursoInscripto',
        ),
        migrations.DeleteModel(
            name='CursoInscripto',
        ),
        migrations.DeleteModel(
            name='inscripcion',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
