# Generated by Django 4.2.5 on 2023-11-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_inscripcion_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='estudiantes',
            field=models.ManyToManyField(through='courses.Inscripcion', to='courses.estudiante'),
        ),
    ]
