# Generated by Django 4.2.5 on 2023-11-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_habilitado_inscripcion_course_estudiantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='estudiantes',
            new_name='estudiantesInscripto',
        ),
    ]
