# Generated by Django 4.2.5 on 2023-11-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_estudiantes_course_estudiantesinscripto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='nombre',
        ),
    ]
