# Generated by Django 4.2.5 on 2023-11-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_inscripcion_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name_plural': 'Inscripciones'},
        ),
    ]
